Update connection.py
A better way to determine the protocol type for the remote host and port. With the current version if you didn't specify the protocol and you are trying to connect to port 8777 (Viya version 3.4) you will get the following error because your protocol will be set to "cas" automatically, which isn't correct.

conn = swat.CAS('example.sas.com', port=8777, username="alexal", password="password")
ERROR: The TCP/IP negClientSSL support routine failed with status 90bfc0e0.
ERROR: Failed to connect to host 'example.sas.com', port 8777.
Traceback (most recent call last):
File "", line 1, in
File "/usr/lib/python2.7/site-packages/swat/cas/connection.py", line 297, in init
raise SWATError(self._sw_error.getLastErrorMessage())
swat.exceptions.SWATError: Could not connect to 'example.sas.com' on port 8777.